[package]
name = "prepayment"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0", features = ["serde"] }
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36"
serde = { version = "1.0", features = ["derive"] }
